insert into SanPham_DongSP(MaSP, DongSP) values (1, N'Sản phẩm từ Úc')
insert into SanPham_DongSP(MaSP, DongSP) values (2, N'Sản phẩm từ Mỹ')
insert into SanPham_DongSP(MaSP, DongSP) values (3, N'Sản phẩm từ Ấn Độ')
insert into SanPham_DongSP(MaSP, DongSP) values (4, N'Sản phẩm từ Canada')
insert into SanPham_DongSP(MaSP, DongSP) values (5, N'Sản phẩm từ Malaysia')
insert into SanPham_DongSP(MaSP, DongSP) values (6, N'Sản phẩm từ Lào')
insert into SanPham_DongSP(MaSP, DongSP) values (7, N'Sản phẩm từ Campu')
insert into SanPham_DongSP(MaSP, DongSP) values (8, N'Sản phẩm từ Hà Lan')
insert into SanPham_DongSP(MaSP, DongSP) values (9, N'Sản phẩm từ Thái Lan')
insert into SanPham_DongSP(MaSP, DongSP) values (10, N'Sản phẩm từ Đài Loan')

