insert into SanPham_MauSac(MaSP, Mau) values (1, N'Đỏ')
insert into SanPham_MauSac(MaSP, Mau) values (2, N'Nâu')
insert into SanPham_MauSac(MaSP, Mau) values (3, N'Trắng')
insert into SanPham_MauSac(MaSP, Mau) values (4, N'Cam')
insert into SanPham_MauSac(MaSP, Mau) values (5, N'Tràm')
insert into SanPham_MauSac(MaSP, Mau) values (6, N'Lục')
insert into SanPham_MauSac(MaSP, Mau) values (7, N'Lam')
insert into SanPham_MauSac(MaSP, Mau) values (8, N'Tím')
insert into SanPham_MauSac(MaSP, Mau) values (9, N'Đen')
insert into SanPham_MauSac(MaSP, Mau) values (10, N'Xanh da trời')
