/* ------------------------------------------------------------
   Description:  Script for object(s)
     Tables:
          [dbo].[LoaiHang]
   Database DESKTOP-7C65RST.Shopee

   ------------------------------------------------------------ */

BEGIN TRAN 
-- =======================================================
-- Inserting script for Table: [dbo].[LoaiHang]
-- =======================================================
SET QUOTED_IDENTIFIER OFF
Print "Inserting Script for Table: [dbo].[LoaiHang]"
SET QUOTED_IDENTIFIER ON
insert into LoaiHang(MaLH, TenLH, MaDM) values (1, N'Tốt', 1)
insert into LoaiHang(MaLH, TenLH, MaDM) values (2, N'Tốt', 2)
insert into LoaiHang(MaLH, TenLH, MaDM) values (3, N'Tốt', 3)
insert into LoaiHang(MaLH, TenLH, MaDM) values (4, N'Tốt', 4)
insert into LoaiHang(MaLH, TenLH, MaDM) values (5, N'Tốt', 5)

insert into LoaiHang(MaLH, TenLH, MaDM) values (6, N'Xuất sắc', 6)
insert into LoaiHang(MaLH, TenLH, MaDM) values (7, N'Xuất sắc', 7)
insert into LoaiHang(MaLH, TenLH, MaDM) values (8, N'Xuất sắc', 8)
insert into LoaiHang(MaLH, TenLH, MaDM) values (9, N'Xuất sắc', 9)
insert into LoaiHang(MaLH, TenLH, MaDM) values (10, N'Xuất sắc', 10)
insert into LoaiHang(MaLH, TenLH, MaDM) values (11, N'Xuất sắc', 11)
insert into LoaiHang(MaLH, TenLH, MaDM) values (12, N'Xuất sắc', 12)
insert into LoaiHang(MaLH, TenLH, MaDM) values (13, N'Xuất sắc', 13)
insert into LoaiHang(MaLH, TenLH, MaDM) values (14, N'Xuất sắc', 14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (15,N'Xuất sắc',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (16,N'Trung cấp',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (17,N'Cao cấp',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (18,N'Tốt',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (19,N'Xuất sắc',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (20,N'Tốt',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (21,N'Xuất sắc',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (22,N'Cao cấp',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (23,N'Tốt',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (24,N'Tốt',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (25,N'Tốt',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (26,N'Cao cấp',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (27,N'Tốt',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (28,N'Cao cấp',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (29,N'Tốt',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (30,N'Cao cấp',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (31,N'Tốt',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (32,N'Trung cấp',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (33,N'Trung cấp',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (34,N'Xuất sắc',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (35,N'Cao cấp',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (36,N'Cao cấp',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (37,N'Tốt',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (38,N'Xuất sắc',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (39,N'Tốt',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (40,N'Cao cấp',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (41,N'Cao cấp',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (42,N'Cao cấp',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (43,N'Cao cấp',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (44,N'Xuất sắc',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (45,N'Tốt',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (46,N'Xuất sắc',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (47,N'Trung cấp',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (48,N'Xuất sắc',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (49,N'Xuất sắc',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (50,N'Xuất sắc',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (51,N'Trung cấp',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (52,N'Trung cấp',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (53,N'Tốt',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (54,N'Cao cấp',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (55,N'Cao cấp',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (56,N'Tốt',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (57,N'Tốt',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (58,N'Tốt',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (59,N'Xuất sắc',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (60,N'Xuất sắc',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (61,N'Tốt',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (62,N'Cao cấp',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (63,N'Xuất sắc',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (64,N'Xuất sắc',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (65,N'Cao cấp',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (66,N'Cao cấp',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (67,N'Xuất sắc',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (68,N'Trung cấp',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (69,N'Tốt',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (70,N'Xuất sắc',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (71,N'Cao cấp',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (72,N'Trung cấp',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (73,N'Tốt',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (74,N'Cao cấp',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (75,N'Cao cấp',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (76,N'Xuất sắc',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (77,N'Xuất sắc',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (78,N'Trung cấp',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (79,N'Trung cấp',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (80,N'Cao cấp',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (81,N'Trung cấp',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (82,N'Tốt',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (83,N'Xuất sắc',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (84,N'Xuất sắc',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (85,N'Trung cấp',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (86,N'Trung cấp',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (87,N'Trung cấp',3)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (88,N'Trung cấp',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (89,N'Xuất sắc',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (90,N'Tốt',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (91,N'Tốt',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (92,N'Tốt',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (93,N'Trung cấp',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (94,N'Xuất sắc',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (95,N'Cao cấp',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (96,N'Xuất sắc',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (97,N'Cao cấp',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (98,N'Tốt',6)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (99,N'Xuất sắc',5)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (100,N'Cao cấp',11)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (101,N'Cao cấp',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (102,N'Tốt',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (103,N'Tốt',10)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (104,N'Xuất sắc',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (105,N'Trung cấp',1)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (106,N'Xuất sắc',2)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (107,N'Cao cấp',14)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (108,N'Cao cấp',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (109,N'Cao cấp',12)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (110,N'Cao cấp',8)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (111,N'Tốt',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (112,N'Cao cấp',9)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (113,N'Xuất sắc',7)
INSERT INTO [dbo].[LoaiHang]([MaLH],[TenLH],[MaDM]) VALUES (114,N'Xuất sắc',14)
GO
-- TRANSACTION HANDLING
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO
IF @@TRANCOUNT>0
	COMMIT

SET NOEXEC OFF
GO
